spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        show_sql: true
        format_sql: true
    open-in-view: true
    show-sql: true

  datasource:
    url: ${URL}
    driver-class-name: ${DRIVER_CLASS_NAME}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

server:
  port: ${PORT_NUMBER}
